version: "3.0"
services:
 
#nginx, 80
  zhiwei-nginx:
    container_name: "my-nginx"
    image: "${PREFIX}/my-nginx:0.1"
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8870:8870"
    expose:
     - "80"
     - "8870"
    networks:
      default:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      #- ./nginx/www:/var/www
    deploy:
      placement:
        constraints: [node.HOSTNAME == docker2]
    restart: unless-stopped

  
  
networks:
   default:
     external:
       name: mynet