version: '3'
services:
    jenkins:
     #image: 'jenkins/jenkins:lts'
     image: 'zhiwei-jenkins:0.1'
     container_name: jenkins
     restart: always
     environment:
      TZ: "Asia/Shanghai"
     ports:
      - '9999:8080'
      - '50000:50000'
     expose:
      - 9999
     volumes:
      - '/mnt/zw-docker/jenkins/data:/var/jenkins_home'
      - '/mnt/zw-docker/softwares/maven3:/var/maven_home'
      - '/mnt/zw-docker/softwares/repository:/var/repository'